# ========
# VALIDATE
# ========

name: Validate

# Activation Events
# =================

on: # Validate on any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
  workflow_dispatch:

# Jobs
# ====

jobs:
  # Check the build/ci process works properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run build

      # Push Changes 🌎
      # ===============
      - name: check for changes
        id: git-diff
        run: |
          if git diff --exit-code; then
            echo "::set-output name=changes_exist::false"
          else
            echo "::set-output name=changes_exist::true"
          fi

      - name: push
        if: ${{ steps.git-diff.outputs.changes_exist == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Build 📦'
          git push

  # make sure the action works on a clean machine without building
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dry-run: true
          slots: |
            inputs: Hello World
